import Link from "next/link";
import { ArrowRight, ArrowUpRight } from "lucide-react";
import { PageIntro } from "@/components/ui";

export const metadata = { title: "知识库学习方法与书籍依据" };
const books = [
  { title: "Make It Stick", author: "Brown、Roediger、McDaniel · 2014", url: "https://www.makeitstick.com/", idea: "把熟悉感与能从记忆中写出来分开。", action: "先尝试回忆，再查看参考；把同一知识的练习分散到不同日期。" },
  { title: "Understanding How We Learn", author: "Weinstein、Sumeracki、Caviglioli · 2019", url: "https://www.routledge.com/Understanding-How-We-Learn-A-Visual-Guide/Weinstein-Sumeracki-Caviglioli/p/book/9781138561694", idea: "把研究支持的记忆与理解策略变成可以完成的动作。", action: "解释和例子放在一起，每条知识都提供自己的输出与对照。" },
  { title: "How Learning Happens", author: "Kirschner、Hendrick · 第二版，2024", url: "https://www.routledge.com/How-Learning-Happens-Seminal-Works-in-Educational-Psychology-and-What-/A-Kirschner-Hendrick/p/book/9781032498409", idea: "根据已有知识与当前任务提供支持。", action: "第一次接触可先看示例；有基础时先输出，再逐步减少提示。" },
  { title: "Cognitive Load Theory", author: "Sweller、Ayres、Kalyuga · 2011", url: "https://link.springer.com/book/10.1007/978-1-4419-8126-4", idea: "避免同时要求学生处理过多陌生内容。", action: "每次最多两条，先完成一个主要任务；来源和次要说明按需展开。" },
];
export default function Page() {
  return <div className="stack"><div className="breadcrumb"><Link href="/knowledge">知识库</Link><span>/</span><span>学习方法</span></div><PageIntro eyebrow="RESEARCH INTO PRACTICE" title="让复习服务于写作" description="每条知识都要能回答：表达什么、何时适用、怎样写、什么时候不能用。"/><section className="panel stack"><h2>你实际需要完成的四步</h2><ol><li><strong>理解：</strong>读一个短例子，弄清意思和使用条件。</li><li><strong>回忆：</strong>隐藏参考，写出自己的表达；第一次接触时可以先看示例。</li><li><strong>应用：</strong>换一个情境，再写自己的句子，核对意思、搭配和边界。</li><li><strong>再检验：</strong>隔一段时间回忆，并在未见过的题目里独立写作。</li></ol><p className="fine">短练习中的应用紧接参考，属于有准备的练习。它不能代替延迟后的独立新题评价。</p><Link href="/knowledge/practice" className="button primary">做一次短练习 <ArrowRight size={15}/></Link></section><div className="knowledge-grid">{books.map((book) => <article className="panel stack" key={book.title}><p className="eyebrow">BOOK → DESIGN</p><h3 className="english">{book.title}</h3><p className="fine">{book.author}</p><p>{book.idea}</p><p><strong>在这里：</strong>{book.action}</p><a className="text-link" href={book.url} target="_blank" rel="noreferrer">作者 / 出版社资源 <ArrowUpRight size={14}/></a></article>)}</div><section className="panel stack"><h2>研究支持到哪里？</h2><p>检索与间隔研究支持记忆练习的设计理由；提示渐退与示例研究提醒我们照顾基础和任务复杂性。这些书籍是研究综合与教学解读，页面基于核验的书目、目录和公开资源，没有宣称逐章审读全部书籍。</p><p>写作还要求选对内容、解释理由、组织篇章。背出一个短语、勾选自查或觉得熟悉，都不能证明整篇作文能力已经提高。</p><ul><li><a className="text-link" href="https://onlinelibrary.wiley.com/doi/abs/10.1111/lang.12479" target="_blank" rel="noreferrer">二语间隔练习元分析</a>：收益随活动、学习目标与测评延迟变化。</li><li><a className="text-link" href="https://pdf.retrievalpractice.org/transfer/Pan_Rickard_2018.pdf" target="_blank" rel="noreferrer">检索练习的迁移元分析</a>：记忆练习向新任务迁移有条件。</li><li><a className="text-link" href="https://pubmed.ncbi.nlm.nih.gov/23121446/" target="_blank" rel="noreferrer">复杂示例学习的边界实验</a>：不能把“越早困难检索越好”套到所有初学者。</li></ul><p className="fine">复习间隔采用可解释的历史自评规则，尚未拟合个人记忆模型；没有脑区、永久记忆、最佳间隔或提分保证。实际效果需要相近学习投入、延迟新题和可靠的外部评价。</p></section></div>;
}
